### ISSUE TITLE
is there any possible to convert pth model to onnx model?

### ISSUE THREAD

**Issue by jcyhcs** [VictorSheverdin/Calibration#2]
hi,professor:
i look into your code, there use onnx models, but superglue official have pth weights, so , how can i convert pth weights to onnx model , so i can use your code project? oh,please help me!

**Comment by gjgjh** [comment]
> hi,professor: i look into your code, there use onnx models, but superglue official have pth weights, so , how can i convert pth weights to onnx model , so i can use your code project? oh,please help me!

Have you solved it? I had the same problem here :-)
